#1. Env setttings
import os
env=Environment(ENV=os.environ)
#2. Targets
env.Program(target='gtest01', source='gtest01.cpp', LIBS=['gtest', 'gtest_main', 'pthread'])
env.Program(target='gtest02', source='gtest02.cpp', LIBS=['gtest', 'pthread'])
