/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpp2java */

#ifndef _Included_cpp2java
#define _Included_cpp2java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp2java
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cpp2java_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
