// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialize.proto

#ifndef PROTOBUF_INCLUDED_serialize_2eproto
#define PROTOBUF_INCLUDED_serialize_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_serialize_2eproto 

namespace protobuf_serialize_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_serialize_2eproto
namespace lm {
class hello;
class helloDefaultTypeInternal;
extern helloDefaultTypeInternal _hello_default_instance_;
}  // namespace lm
namespace google {
namespace protobuf {
template<> ::lm::hello* Arena::CreateMaybeMessage<::lm::hello>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace lm {

// ===================================================================

class hello : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lm.hello) */ {
 public:
  hello();
  virtual ~hello();

  hello(const hello& from);

  inline hello& operator=(const hello& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  hello(hello&& from) noexcept
    : hello() {
    *this = ::std::move(from);
  }

  inline hello& operator=(hello&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const hello& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const hello* internal_default_instance() {
    return reinterpret_cast<const hello*>(
               &_hello_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(hello* other);
  friend void swap(hello& a, hello& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline hello* New() const final {
    return CreateMaybeMessage<hello>(NULL);
  }

  hello* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<hello>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const hello& from);
  void MergeFrom(const hello& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(hello* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string str = 2 [default = "abc"];
  bool has_str() const;
  void clear_str();
  static const int kStrFieldNumber = 2;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  #if LANG_CXX11
  void set_str(::std::string&& value);
  #endif
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // optional int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // optional int32 op = 3 [default = 15];
  bool has_op() const;
  void clear_op();
  static const int kOpFieldNumber = 3;
  ::google::protobuf::int32 op() const;
  void set_op(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lm.hello)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_str();
  void clear_has_str();
  void set_has_op();
  void clear_has_op();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  public:
  static ::google::protobuf::internal::ExplicitlyConstructed< ::std::string> _i_give_permission_to_break_this_code_default_str_;
  private:
  ::google::protobuf::internal::ArenaStringPtr str_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 op_;
  friend struct ::protobuf_serialize_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// hello

// optional int32 id = 1;
inline bool hello::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void hello::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void hello::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void hello::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 hello::id() const {
  // @@protoc_insertion_point(field_get:lm.hello.id)
  return id_;
}
inline void hello::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:lm.hello.id)
}

// required string str = 2 [default = "abc"];
inline bool hello::has_str() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void hello::set_has_str() {
  _has_bits_[0] |= 0x00000001u;
}
inline void hello::clear_has_str() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void hello::clear_str() {
  str_.ClearToDefaultNoArena(&::lm::hello::_i_give_permission_to_break_this_code_default_str_.get());
  clear_has_str();
}
inline const ::std::string& hello::str() const {
  // @@protoc_insertion_point(field_get:lm.hello.str)
  return str_.GetNoArena();
}
inline void hello::set_str(const ::std::string& value) {
  set_has_str();
  str_.SetNoArena(&::lm::hello::_i_give_permission_to_break_this_code_default_str_.get(), value);
  // @@protoc_insertion_point(field_set:lm.hello.str)
}
#if LANG_CXX11
inline void hello::set_str(::std::string&& value) {
  set_has_str();
  str_.SetNoArena(
    &::lm::hello::_i_give_permission_to_break_this_code_default_str_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lm.hello.str)
}
#endif
inline void hello::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_str();
  str_.SetNoArena(&::lm::hello::_i_give_permission_to_break_this_code_default_str_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lm.hello.str)
}
inline void hello::set_str(const char* value, size_t size) {
  set_has_str();
  str_.SetNoArena(&::lm::hello::_i_give_permission_to_break_this_code_default_str_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lm.hello.str)
}
inline ::std::string* hello::mutable_str() {
  set_has_str();
  // @@protoc_insertion_point(field_mutable:lm.hello.str)
  return str_.MutableNoArena(&::lm::hello::_i_give_permission_to_break_this_code_default_str_.get());
}
inline ::std::string* hello::release_str() {
  // @@protoc_insertion_point(field_release:lm.hello.str)
  if (!has_str()) {
    return NULL;
  }
  clear_has_str();
  return str_.ReleaseNonDefaultNoArena(&::lm::hello::_i_give_permission_to_break_this_code_default_str_.get());
}
inline void hello::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    set_has_str();
  } else {
    clear_has_str();
  }
  str_.SetAllocatedNoArena(&::lm::hello::_i_give_permission_to_break_this_code_default_str_.get(), str);
  // @@protoc_insertion_point(field_set_allocated:lm.hello.str)
}

// optional int32 op = 3 [default = 15];
inline bool hello::has_op() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void hello::set_has_op() {
  _has_bits_[0] |= 0x00000004u;
}
inline void hello::clear_has_op() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void hello::clear_op() {
  op_ = 15;
  clear_has_op();
}
inline ::google::protobuf::int32 hello::op() const {
  // @@protoc_insertion_point(field_get:lm.hello.op)
  return op_;
}
inline void hello::set_op(::google::protobuf::int32 value) {
  set_has_op();
  op_ = value;
  // @@protoc_insertion_point(field_set:lm.hello.op)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace lm

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_serialize_2eproto
