#1. Env setttings
import os
env=Environment(ENV=os.environ, STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME = 'yes')
env.Append(LIBPATH=".")
#2. Targets
singleton=env.Object('singleton.cpp')
singletonMain=env.Object('singletonMain.cpp')
env.Program('singletonFromObject',source=[singleton, singletonMain])

env.StaticLibrary('singletonStatic',source=singleton)
env.SharedLibrary('singletonDynamic',source=singleton)

# static链接过程会优化掉没有直接reference的代码
env.Program('singletonFromStatic',source=singletonMain,LIBS=['singletonStatic'])
env.Program('singletonFromDynamic',source=singletonMain,LIBS=['singletonDynamic'])