cc_binary(
    name = "producerConsumer",
    srcs = ["producerConsumer.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testCondWait",
    srcs = ["testCondWait.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthread",
    srcs = ["testPthread.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthreadCancel",
    srcs = ["testPthreadCancel.c"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthreadCancelCpp",
    srcs = ["testPthreadCancelCpp.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthreadCancelCppStd",
    srcs = ["testPthreadCancelCppStd.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthreadCancelUnwind",
    srcs = ["testPthreadCancelUnwind.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthreadCond",
    srcs = ["testPthreadCond.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthreadExit",
    srcs = ["testPthreadExit.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthreadJoin",
    srcs = ["testPthreadJoin.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthreadMutex",
    srcs = ["testPthreadMutex.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPthreadReturn",
    srcs = ["testPthreadReturn.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "useTlsCheck",
    srcs = ["useTlsCheck.cpp", "useTlsCreate.h", "useTlsCreate.cpp"],
    linkopts = ["-lpthread"],
)
cc_binary(
    name = "usetls",
    srcs = ["usetls.cpp"],
    linkopts = ["-lpthread"]
)
