#1. Env setttings
import os
env=Environment(ENV=os.environ)
env.Append(CCFLAGS="-I/usr/local/include")
linuxlibs  = ['xml2','snappy','protobuf','lz4','zstd','jvm','double-conversion']
#2. Targets
env.Program(target='testleveldb',source='testleveldb.cpp',LIBS='leveldb')
cflags=os.popen("xml2-config --cflags").read()
lflags=os.popen("xml2-config --exec-prefix=/usr --libs").read()
env.Append(CCFLAGS=cflags)
env.Append(LINKFLAGS=lflags)
env.Program(target='testlibxml2', source='testlibxml2.cpp')
env.Program(target='testlz4',     source='testlz4.cpp',    LIBS='lz4')
env.Program(target='testsnappy',  source='testsnappy.cpp', LIBS='snappy')
env.Program(target='testzstd',    source='testzstd.cpp',   LIBS='zstd')
