#1. Env setttings
import os
env=Environment(ENV=os.environ)
env.Append(CXXFLAGS="--std=c++14")
#2. Targets
#env.Program(target='atomics', source='atomics.cpp',LIBS='pthread')
env.Program(target='autoReturn', source='autoReturn.cpp')
env.Program(target='bindImpl', source='bindImpl.cpp')
env.Program(target='decltypeAuto', source='decltypeAuto.cpp')
env.Program(target='indexSequence', source='indexSequence.cpp')
env.Program(target='newLambda', source='newLambda.cpp')
env.Program(target='pv', source='pv.cpp',LIBS='pthread')
env.Program(target='testStdThread', source='testStdThread.cpp',LIBS='pthread')
env.Program(target='threadFuture', source='threadFuture.cpp',LIBS='pthread')
env.Program(target='usepackagedtask', source='usepackagedtask.cpp',LIBS='pthread')
env.Program(target='usepromise', source='usepromise.cpp',LIBS='pthread')
env.Program(target='userDefinedLiteral', source='userDefinedLiteral.cpp')