cc_binary(
    name = "testAlarm",
    srcs = ["testAlarm.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testAlarmFork",
    srcs = ["testAlarmFork.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testDup",
    srcs = ["testDup.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPipeAlarm",
    srcs = ["testPipeAlarm.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testPoll",
    srcs = ["testPoll.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testSelect",
    srcs = ["testSelect.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "threads_cacheline",
    srcs = ["threads_cacheline.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "threads_lock",
    srcs = ["threads_lock.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "threads_omp",
    srcs = ["threads_omp.cpp"],
    copts = ["-fopenmp"],
    linkopts = ["-lpthread -lomp"]
)
