#1. Env setttings
import os
env=Environment(ENV=os.environ)
env.Append(CXXFLAGS="--std=c++11")
#2. Targets
env.Program(target='testAlarm', source='testAlarm.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='testAlarmFork', source='testAlarmFork.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='testDup', source='testDup.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='testPipeAlarm', source='testPipeAlarm.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='testPoll', source='testPoll.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='testSelect', source='testSelect.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='threads_cacheline', source='threads_cacheline.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='threads_lock', source='threads_lock.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='threads_omp', source='threads_omp.cpp', LIBS=['atomic', 'pthread'])
