#1. Env setttings
import os
env=Environment(ENV=os.environ)
env.Append(CPPPATH=['./include'])
env.Append(CPPPATH=['.'])
JAVA_HOME=env['ENV']['JAVA_HOME']
env.Append(CPPPATH=[JAVA_HOME+'/include'])
env.Append(CPPPATH=[JAVA_HOME+'/include/linux'])
env.Append(LIBPATH=[JAVA_HOME+'/jre/lib/amd64/server'])
linuxlibs  = ['jvm']
env.Program(target="usejclass",  source=['usejclass.cpp'],  LIBS=[linuxlibs])
env.SharedLibrary(target="impl", source=['impl.c'])
