//e = SSTREAM "local/users/limgong/02_Joined_uet_AttributedAndUnattributed_20190721_0000.detail.ss"; //Output.ss";
e = SSTREAM "local/users/limgong/Test/011_Attributed_20190728_0000.detail.ss"; //Output.ss";
/*
s =
    SELECT DISTINCT ConversionId
    FROM e;
*/
/*
s =
    SELECT *
    FROM e // 179135/179135  180770/Same
    WHERE EventKey = "e33a3a83e4235d9d898eff8c00606761";
*/
/*
s =
    SELECT *
    FROM e
    WHERE IsAttributed == false;
*/

s = // AttributedAndUnattributed_Joined_uet_pii_20190721_0000.detail.ss
    SELECT *
    FROM e
    WHERE CleanedClickId == "0023ce8a0641189a8fe093bee833b9c2";// AND ConversionId == "6c301690d6225279261902b7f631a01c5c4aea87da1214a902fe99ed84b81996";

/*
s =
    SELECT *, COUNT(ConversionId) AS C
    FROM e
    GROUP BY ConversionId
    HAVING C > 1;
*/
/*
s =
    SELECT DISTINCT ConversionId
    FROM e;
s =
    SELECT COUNT() AS C
    FROM s;//172910
*/

//s = SELECT DISTINCT TagId FROM e;
/*
s =
    SELECT *
    FROM e
    WHERE IsAttributed == false;
*/
OUTPUT s TO CONSOLE;
//OUTPUT s TO SSTREAM "local/users/limgong/Unattributed_Joined_uet_pii_20190721_0000.detail.ss";
