DEFINE MODULE myModule
BEGIN
VIEW viewInModule
    RETURN ROWSET (UserId:int, Start:DateTime, Region:string, Query:string, Duration:int, Urls:string, ClickedUrls:string)
    PARAMS ();

VIEW searchLogParameterizedView
RETURN ROWSET(UserId:int, Start:DateTime, Region:string, Query:string, Duration:int, Urls:string, ClickedUrls:string)
PARAMS (
	start string,
	end string
);

END MODULE
////////////////////////

VIEW viewInModule
RETURN ROWSET(UserId:int, Start:DateTime, Region:string, Query:string, Duration:int, Urls:string, ClickedUrls:string)
PARAMS () 
BEGIN
    rawdata = 
        EXTRACT UserId:int, Start:DateTime, Region:string, Query:string, Duration:int, Urls:string, ClickedUrls:string
        FROM @"SearchLog.txt"
        USING DefaultTextExtractor();
END VIEW

VIEW searchLogParameterizedView
RETURN ROWSET(UserId:int, Start:DateTime, Region:string, Query:string, Duration:int, Urls:string, ClickedUrls:string)
PARAMS (
	start string,
	end string
)
BEGIN
    searchlog = VIEW "SearchLog.view";
    filtered_searchlog =
        SELECT *
        FROM searchlog
        WHERE Start >= DateTime.Parse(@start) AND Start < DateTime.Parse(@end).AddDays(1);
END VIEW