searchlog =
    EXTRACT 
        UserId : int,
        name : string
    //        FROM "TextFile1.txt",
    //             "TextFile2.txt"
    FROM STREAMSET "/"
         PATTERN "TextFile%n.txt"
         RANGE __serialnum = ["1", "2"]
    USING DefaultTextExtractor(delimiter:' ');

searchlog1 =
    VIEW "Scope2.view";

OUTPUT searchlog
TO "output/searchlog.txt"
USING DefaultTextOutputter();
OUTPUT searchlog1
TO "output/searchlog1.txt"
USING DefaultTextOutputter();
