#1. Env setttings
import os
env=Environment(ENV=os.environ)
env.Append(CXXFLAGS="--std=c++98")
#2. Targets
for f in env.Glob("*.cpp"):
    if "error" not in str(f):
    	env.Program("${SOURCE.base}",f)
