DEFINE MODULE GenData
BEGIN

VIEW genEmployee
RETURN ROWSET(EmpName:string, DeptId:int)
PARAMS();

VIEW genDepartment
RETURN ROWSET(DeptId: int, DepName: string)
PARAMS();

VIEW genDepartments
RETURN ROWSET (DeptId: int, DepNames:ARRAY<string>)
PARAMS();
END MODULE
//////////////////////////
VIEW genEmployee
RETURN ROWSET(EmpName:string, DeptId:int)
PARAMS()
BEGIN
    Employees =
    SELECT EmpName,
           DeptId
    FROM(
        VALUES
        (
            "Rafferty",
            31
        ),

        (
            "Jones",
            34
        ),

        (
            "Steinberg",
            31
        ),

        (
            "Robinson",
            34
        ),

        (
            "Smith",
            34
        ),

        (
            "John",
            31
        )
    ) AS Employees(EmpName, DeptId);
END VIEW

VIEW genDepartment
RETURN ROWSET(DeptId: int, DepName: string)
PARAMS()
BEGIN
    Departments =
        SELECT DeptId, DepName
        FROM(
            VALUES
            (
                31,
                "math, mandarine"
            ),
            (
                34,
                "physics, chemistry"
            )
    ) AS Departments(DeptId, DepName);
END VIEW

VIEW genDepartments
RETURN ROWSET (DeptId: int, DepNames:ARRAY<string>)
PARAMS()
BEGIN
    data =
        genDepartment
        (
        );
    data1 =
        SELECT DeptId,
               DepName.Split(new[]{ ',' }) AS DepNames
        FROM data;
    data2 =
        SELECT DeptId,
               new ARRAY<string>(DepNames) AS DepNames;
END VIEW