DEFINE MODULE GenData
BEGIN

VIEW gen
RETURN ROWSET(EmpName:string, DeptId:int)
PARAMS();
END MODULE

VIEW gen
RETURN ROWSET(EmpName:string, DeptId:int)
PARAMS()
BEGIN
    Employees =
    SELECT EmpName,
           DeptId
    FROM(
        VALUES
        (
            "Rafferty",
            31
        ),

        (
            "Jones",
            34
        ),

        (
            "Steinberg",
            31
        ),

        (
            "Robinson",
            34
        ),

        (
            "Smith",
            34
        ),

        (
            "John",
            31
        )
    ) AS Employees(EmpName, DeptId);
END VIEW