DEFINE MODULE GenData
BEGIN

VIEW genEmployee
RETURN ROWSET(EmpName:string, DeptId:int)
PARAMS();

VIEW genDepartment
RETURN ROWSET(DeptId int, DepName string)
PARAMS();

END MODULE

VIEW genEmployee
RETURN ROWSET(EmpName:string, DeptId:int)
PARAMS()
BEGIN
    Employees =
    SELECT EmpName,
           DeptId
    FROM(
        VALUES
        (
            "Rafferty",
            31
        ),

        (
            "Jones",
            34
        ),

        (
            "Steinberg",
            31
        ),

        (
            "Robinson",
            34
        ),

        (
            "Smith",
            34
        ),

        (
            "John",
            31
        )
    ) AS Employees(EmpName, DeptId);
END VIEW

VIEW genDepartment
RETURN ROWSET(DeptId int, DepName string)
PARAMS()
BEGIN
    Departments =
        SELECT DeptId, DepName
        FROM(
            VALUES
            (
                31,
                "math"
            ),
            (
                34,
                "physics"
            )
    ) AS Departments(DeptId, DepName);
END VIEW