#1. Env setttings
import os
env=Environment(ENV=os.environ)
env.Append(CXXFLAGS="--std=c++11")
#2. Targets
env.Program(target='client', source='client.cpp')
env.Program(target='server', source='server.cpp')
env.Program(target='testAioNotify', source='testAioNotify.cpp')
env.Program(target='testAioQuery', source='testAioQuery.cpp')
env.Program(target='testEpoll', source='testEpoll.cpp')
env.Program(target='testLibEv', source='testLibEv.cpp')
env.Program(target='testLibEvent', source='testLibEvent.cpp')
env.Program(target='testLibEventHttp', source='testLibEventHttp.cpp')
env.Program(target='testPipeEv', source='testPipeEv.cpp')
env.Program(target='testRWlock', source='testRWlock.cpp')
env.Program(target='testcwd', source='testcwd.cpp')
env.Program(target='unixDomainSocket', source='unixDomainSocket.cpp')
