import os,sys
env = Environment(ENV = {'PATH' : os.environ['PATH']})
env.Append(CXXFLAGS="-Wall")
env.Append(CXXFLAGS="-Werror")

env.SConscript(dirs=['cpp98'])
env.SConscript(dirs=['datastructure'])
if os.system("./testgmock.sh") == 0:
    env.SConscript(dirs=['gtest'])
env.SConscript(dirs=['linkerDiff'])
env.SConscript(dirs=['linkerDynamic'])
env.SConscript(dirs=['jni'])

#if os.system("./testcpp.sh 11") == 0:
#    env.SConscript(dirs=['cpp11'])
#if os.system("./testcpp.sh 14") == 0:
#    env.SConscript(dirs=['cpp14'])
#if os.system("./testcpp.sh 17") == 0:
#    env.SConscript(dirs=['cpp17'])

env = Environment(CFLAGS='-std=c++11')
conf = Configure(env)
if conf.CheckCXX():
   print("Yes CXX11")
   env.SConscript(dirs=['cpp11'])
env = conf.Finish()

env = Environment(CFLAGS='-std=c++14')
conf = Configure(env)
if conf.CheckCXX():
   print("Yes CXX14")
   env.SConscript(dirs=['cpp14'])
env = conf.Finish()

env = Environment(CFLAGS='-std=c++17')
conf = Configure(env)
if conf.CheckCXX():
   print("Yes CXX17")
   env.SConscript(dirs=['cpp17'])
env = conf.Finish()