import os,sys
env = Environment(ENV = {'PATH' : os.environ['PATH']})
env.Append(CXXFLAGS="-Wall")
env.Append(CXXFLAGS="-Werror")
env.SConscript(dirs=['cpp98'])
env.SConscript(dirs=['cpp11'])
env.SConscript(dirs=['linker'])
env.SConscript(dirs=['datastructure'])
env.SConscript(dirs=['multiplex/posix'])
env.SConscript(dirs=['multiplex/pthread'])
env.SConscript(dirs=['protobuf'])
if sys.platform.find('linux')==0:
    env.SConscript(dirs=['multiplex/linux'])
else:
    env.SConscript(dirs=['3p'])
    env.SConscript(dirs=['cpp14'])
