#1. Env setttings
import os
env=Environment(ENV=os.environ)
env.Append(CXXFLAGS="--std=c++17"
#2. Targets
env.Program(target='rwlock', source='rwlock.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='typeDeductionForAutoCpp17', source='typeDeductionForAutoCpp17.cpp', LIBS=['atomic', 'pthread'])
env.Program(target='useVariadic', source='useVariadic.cpp', LIBS=['atomic', 'pthread'])
