cc_binary(
    name = "client",
    srcs = ["client.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "server",
    srcs = ["server.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testAioNotify",
    srcs = ["testAioNotify.cpp"],
    linkopts = ["-lpthread -laio"]
)
cc_binary(
    name = "testAioQuery",
    srcs = ["testAioQuery.cpp"],
    linkopts = ["-lpthread -laio"]
)
cc_binary(
    name = "testEpoll",
    srcs = ["testEpoll.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testLibEv",
    srcs = ["testLibEv.cpp"],
    linkopts = ["-lpthread -lev"]
)
cc_binary(
    name = "testLibEvent",
    srcs = ["testLibEvent.cpp"],
    linkopts = ["-lpthread -levent"]
)
cc_binary(
    name = "testLibEventHttp",
    srcs = ["testLibEventHttp.cpp"],
    linkopts = ["-lpthread -levent"]
)
cc_binary(
    name = "testPipeEv",
    srcs = ["testPipeEv.cpp"],
    linkopts = ["-lpthread -lev"]
)
cc_binary(
    name = "testRWlock",
    srcs = ["testRWlock.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "testcwd",
    srcs = ["testcwd.cpp"],
    linkopts = ["-lpthread"]
)
cc_binary(
    name = "unixDomainSocket",
    srcs = ["unixDomainSocket.cpp"],
    linkopts = ["-lpthread"]
)
