// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

#ifndef PROTOBUF_hello_2eproto__INCLUDED
#define PROTOBUF_hello_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_hello_2eproto();
void protobuf_AssignDesc_hello_2eproto();
void protobuf_ShutdownFile_hello_2eproto();

class hello;

// ===================================================================

class hello : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hello) */ {
 public:
  hello();
  virtual ~hello();

  hello(const hello& from);

  inline hello& operator=(const hello& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const hello& default_instance();

  void Swap(hello* other);

  // implements Message ----------------------------------------------

  inline hello* New() const { return New(NULL); }

  hello* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const hello& from);
  void MergeFrom(const hello& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(hello* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 f1 = 1;
  bool has_f1() const;
  void clear_f1();
  static const int kF1FieldNumber = 1;
  ::google::protobuf::int32 f1() const;
  void set_f1(::google::protobuf::int32 value);

  // required int32 f2 = 2;
  bool has_f2() const;
  void clear_f2();
  static const int kF2FieldNumber = 2;
  ::google::protobuf::int32 f2() const;
  void set_f2(::google::protobuf::int32 value);

  // optional int32 f3 = 3;
  bool has_f3() const;
  void clear_f3();
  static const int kF3FieldNumber = 3;
  ::google::protobuf::int32 f3() const;
  void set_f3(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:hello)
 private:
  inline void set_has_f1();
  inline void clear_has_f1();
  inline void set_has_f2();
  inline void clear_has_f2();
  inline void set_has_f3();
  inline void clear_has_f3();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 f1_;
  ::google::protobuf::int32 f2_;
  ::google::protobuf::int32 f3_;
  friend void  protobuf_AddDesc_hello_2eproto();
  friend void protobuf_AssignDesc_hello_2eproto();
  friend void protobuf_ShutdownFile_hello_2eproto();

  void InitAsDefaultInstance();
  static hello* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// hello

// required int32 f1 = 1;
inline bool hello::has_f1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void hello::set_has_f1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void hello::clear_has_f1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void hello::clear_f1() {
  f1_ = 0;
  clear_has_f1();
}
inline ::google::protobuf::int32 hello::f1() const {
  // @@protoc_insertion_point(field_get:hello.f1)
  return f1_;
}
inline void hello::set_f1(::google::protobuf::int32 value) {
  set_has_f1();
  f1_ = value;
  // @@protoc_insertion_point(field_set:hello.f1)
}

// required int32 f2 = 2;
inline bool hello::has_f2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void hello::set_has_f2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void hello::clear_has_f2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void hello::clear_f2() {
  f2_ = 0;
  clear_has_f2();
}
inline ::google::protobuf::int32 hello::f2() const {
  // @@protoc_insertion_point(field_get:hello.f2)
  return f2_;
}
inline void hello::set_f2(::google::protobuf::int32 value) {
  set_has_f2();
  f2_ = value;
  // @@protoc_insertion_point(field_set:hello.f2)
}

// optional int32 f3 = 3;
inline bool hello::has_f3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void hello::set_has_f3() {
  _has_bits_[0] |= 0x00000004u;
}
inline void hello::clear_has_f3() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void hello::clear_f3() {
  f3_ = 0;
  clear_has_f3();
}
inline ::google::protobuf::int32 hello::f3() const {
  // @@protoc_insertion_point(field_get:hello.f3)
  return f3_;
}
inline void hello::set_f3(::google::protobuf::int32 value) {
  set_has_f3();
  f3_ = value;
  // @@protoc_insertion_point(field_set:hello.f3)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hello_2eproto__INCLUDED
