import os
env=Environment(ENV=os.environ)
env.Append(CXXFLAGS="--std=c++11 -I.")
LINKFLAGS=['-lprotobuf', '-lgrpc', '-lgrpc++']
ex_grpc=Object('examples.grpc.pb.cc')
ex_pb=Object('examples.pb.cc',CCFLAGS="-I. --std=c++11")
env.Program(target='client', CCFLAGS="-I.", source=['client.cpp',ex_grpc,ex_pb], LIBS=LINKFLAGS)
env.Program(target='server', CCFLAGS="-I.", source=['server.cpp',ex_grpc,ex_pb], LIBS=LINKFLAGS)
