import os
env=Environment(ENV=os.environ)

hello=Object('hello.pb.cc',CCFLAGS="-I.")
embed=Object('embed.pb.cc',CCFLAGS="-I.")
serialize=Object('serialize.pb.cc',CCFLAGS="-I.")

env.Program(target='pb_hello',        CCFLAGS="-I.", source=['pb_hello.cpp',hello],        LIBS='protobuf')
env.Program(target='pb_hello_stream', CCFLAGS="-I.", source=['pb_hello_stream.cpp',hello], LIBS='protobuf')
env.Program(target='pb_embed',        CCFLAGS="-I.", source=['pb_embed.cpp', embed],       LIBS='protobuf')
env.Program(target='pb_serialize',    CCFLAGS="-I.", source=['pb_serialize.cpp',serialize],LIBS='protobuf')
