import os
env=Environment(ENV=os.environ)
env.Append(CXXFLAGS="--std=c++11")

hello=Object('hello.pb.cc',CCFLAGS="-I. --std=c++11")
embed=Object('embed.pb.cc',CCFLAGS="-I. --std=c++11")
serialize=Object('serialize.pb.cc',CCFLAGS="-I. --std=c++11")
env.Append(LINKFLAGS="-lprotobuf -lpthread")
env.Program(target='pb_hello',        CCFLAGS="-I.", source=['pb_hello.cpp',hello])
env.Program(target='pb_hello_stream', CCFLAGS="-I.", source=['pb_hello_stream.cpp',hello])
env.Program(target='pb_embed',        CCFLAGS="-I.", source=['pb_embed.cpp', embed])
env.Program(target='pb_serialize',    CCFLAGS="-I.", source=['pb_serialize.cpp',serialize])
