#1. Env setttings
import os
env=Environment(ENV=os.environ)
env.Append(CCFLAGS="-I/usr/local/include")
#2. Targets
#cflags=os.popen("xml2-config --cflags").read()
#lflags=os.popen("xml2-config --exec-prefix=/usr --libs").read()
#env.Append(CCFLAGS=cflags)
#env.Append(LINKFLAGS=lflags)
env.ParseConfig("xml2-config --cflags --exec-prefix=/usr --libs")
