cc_binary(
    name = "fcntlMonitor",
    srcs = ["fcntlMonitor.cpp"],
)
cc_binary(
    name = "mapfile",
    srcs = ["mapfile.c"],
)
cc_binary(
    name = "memexample",
    srcs = ["memexample.cpp"],
)
cc_binary(
    name = "sigcont",
    srcs = ["sigcont.c"],
)
cc_binary(
    name = "testFpe",
    srcs = ["testFpe.cpp"],
)
cc_binary(
    name = "testshare",
    srcs = ["testshare.cpp"],
)
cc_binary(
    name = "usePipe",
    srcs = ["usePipe.cpp"],
)
cc_binary(
    name = "useasm",
    srcs = ["useasm.c"],
)
cc_binary(
    name = "useclone",
    srcs = ["useclone.c"],
)
cc_binary(
    name = "useclone2",
    srcs = ["useclone2.c"],
)
cc_binary(
    name = "usefork",
    srcs = ["usefork.c"],
)
cc_binary(
    name = "usemmap",
    srcs = ["usemmap.c"],
)
cc_binary(
    name = "usevfork",
    srcs = ["usevfork.c"],
)
