import os
env=Environment(ENV=os.environ)
env.Append(CXXFLAGS="--std=c++11 -I/usr/local/include -Ibuild/gen-cpp")

env.Program(target='MyManager_client',source=['build/gen-cpp/MyManager.cpp','workerclient.cpp'], LIBS=['thrift', 'thriftnb', 'event'])
env.Program(target='MyManager_server',source=['build/gen-cpp/MyManager_server.skeleton.cpp', 'build/gen-cpp/MyManager.cpp'], LIBS=['thrift', 'thriftnb', 'event'])

