import os
env=Environment(ENV=os.environ)
LINKFLAGS=['thrift', 'thriftnb', 'event']
env.Append(CXXFLAGS="--std=c++11")
env.Append(CXXFLAGS="-I/usr/local/include")

GEN="build/gen-cpp"
env.Program(target='MyManager_client',source=["%s/MyManager.cpp" % GEN,'workerclient.cpp'], LIBS=LINKFLAGS)
env.Program(target='MyManager_server',source=['%s/MyManager_server.skeleton.cpp' % GEN, '%s/MyManager.cpp' % GEN], LIBS=LINKFLAGS)

