import os
env=Environment(ENV=os.environ)
LINKFLAGS=['thrift', 'thriftnb', 'event']
env.Append(CXXFLAGS="--std=c++11")
env.Append(CXXFLAGS="-I/usr/local/include")
GEN="build/gen-cpp"
myManager=Object("%s/MyManager.cpp" % GEN)
skeleton=Object("%s/MyManager_server.skeleton.cpp" % GEN)
env.Program(target='MyManager_client',source=[myManager, 'workerclient.cpp'], LIBS=LINKFLAGS)
env.Program(target='MyManager_server',source=[myManager, skeleton], LIBS=LINKFLAGS)

