import os,sys
env = Environment(ENV = {'PATH' : os.environ['PATH']})
env.Append(CXXFLAGS="-Wall")
env.Append(CXXFLAGS="-Werror")

env.SConscript(dirs=['multiplex/linux'])
env.SConscript(dirs=['multiplex/posix'])
env.SConscript(dirs=['multiplex/pthread'])
env.SConscript(dirs=['sysv'])
env.Program('useuuid', ['useuuid.cpp'], LIBS=['uuid'])